title: Blog d'Eines Digitals
email: your-email@example.com
description: >-
  Blog sobre eines digitals per a families.
baseurl: "/eines-digitals"
url: "https://ignasi35.github.io"
twitter_username: 
github_username: ignasi35

theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag

minima:
  date_format: "%b %-d, %Y"
  
  social_links:
    - { platform: github,  user_url: "https://github.com/ignasi35" }

header_pages:
  - about.md

show_excerpts: true
